"use client"; // This line marks the file as a Client Component

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Provider } from "@react-spectrum/s2";
import '@react-spectrum/s2/page.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// //export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider background="base"> 
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/person">People</Link>
          </nav>
          <main>{children}</main>
        </div>
      </body>
    </html>
    </Provider>
  );
}
